server:
  port: 8010
spring:
  application:
    name: photo-app-discovery-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false