server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8010/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#gateway:
#  ip: ${GATEWAY_IP}

application:
  security:
    jwt:
      secret: 32e83345d6965be2fcd54b563b2f2a354302a6001bcb7a1f13c014c02b927c680d326b45976b8e899bf56ab1b2f7b2cb1ede0bed251b0b17bb1be6c4fb1587cf7ede801ac083cc548ba3dc818e3ef40c9f8133969fbe66c6d471223dbf665191e56eefc8f9b4f8525526a7941db0d39695632aba1d4dfc1d315d851dca1c78af
      expiration: 300000 #1 day
      refresh-token:
        expiration: 604800000 #7 days